# Setup
title: exist
tagline:
url: https://x.st
baseurl: ""
permalink: /:title/

# Gems
plugins:
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

# Optimize Jekyll
exclude:
  - .editorconfig
  - .git
  - .jekyll-cache
  - Gemfile
  - Gemfile.lock
  - LICENSE.md
  - README.md
  - poole-for-jekyll.gemspec

kramdown:
  math_engine: katex
  math_engine_opts:
    output: html # don't want mathml
    trust: true # allow htmlClass &c.

sass:
  sass_dir: _sass
  style: :compressed

# Options

# Replace this value and uncomment to enable Google Analytics tracking
# ga_analytics: UA-000000-0

# Specify the author for blog posts
author:
  name: Harold Cooper
  url: https://x.st
  email:

# Custom vars
version: 3.0.0
